version: '3.8'

services:
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - grid

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    networks:
      - grid

networks:
  grid:
